### ISSUE TITLE
Implement TOML parser for the config using tomland

### ISSUE THREAD

**Issue by chshersh** [kowainik/crocodealer#6]
~Blocked by #3~

**Comment by Nimor111** [comment]
Hey, since the issue this was blocked by is resolved, is this up for grabs?

**Comment by chshersh** [comment]
@Nimor111 sure, you can take this issue! All data types are implemented, so nothing blocks writing the config for them :slightly_smiling_face:

**Comment by Nimor111** [comment]
Hey, I might need a little help on this one. :/ 
So my idea for the toml config is the following: 

```toml
username = "my-user"
repository = "https://github.com/my-org/my-repo"

[[labelRule]]
  [labelRule.create]
  name = "label1"
  description = "a cool label"
  hexColor = "#000000"

[[labelRule]]
  [labelRule.override]
  old = "old label name"
  new = "new label name"

[[ignoredRepository]]
repo = "https://github.com/my-org/my-ignored-repo"

[[ignoredRepository]]
repo = "https://github.com/my-org/my-other-ignored-repo"
```

The username, repo and ignored repos were trivial enough to implement, but the label rule is really giving me trouble. Since it's a sum type, I figured it would need a custom BiMap as shown [here](https://github.com/kowainik/tomland/blob/master/src/Toml/Bi/Map.hs#L162). But since the `Override` constructor of the `LabelRule` has two arguments I can't really figure out how to write the BiMap for it:

```haskell
-- Here it's ok since it's only one argument
_Create :: TomlBiMap LabelRule Label
_Create = Toml.prism Create matchCreate

matchCreate :: LabelRule -> Either TomlBiMapError Label
matchCreate (Create label) = Right label
matchCreate e              = Toml.wrongConstructor "Create" e

_Override :: TomlBiMap LabelRule ???
_Override = Toml.prism Override matchOverride

matchOverride :: LabelRule -> Either TomlBiMapError ???
matchOverride (Override old new) = Right ???
matchOverride e                  = Toml.wrongConstructor "Override" e
```
And finally, i'm not really clear on how to write a BiMap to AnyValue for Label, since for the _Create BiMap to work I need to be able to convert it to an AnyValue.

I hope i'm not way off base here and thanks.
